version: '3.9'
services:
  api:
    container_name: www-backend-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:14.5
    container_name: postgres
    restart: always
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env

  customer-postgres:
    image: postgres:14.5
    container_name: customer_db
    restart: always
    environment:
      - POSTGRES_USER=customer_db_user
      - POSTGRES_PASSWORD=customer_db_password
    volumes:
      - customer-postgres-vol:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres-vol:
    name: www-backend-db
  customer-postgres-vol:
    name: www-backend-customer-postgres