version: '3.9'
services:
  api:
    container_name: www-backend-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:14.5
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    env_file:
      - .env
volumes:
  postgres:
    name: www-backend-db