version: '3.9'
services:
  postgres:
    image: postgres:14.5
    container_name: customer_db
    restart: always
    environment:
      - POSTGRES_USER=customer_db_user
      - POSTGRES_PASSWORD=customer_db_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5433'
volumes:
  postgres: